version: "3"
services:
  db.mysql:
    container_name: db.mysql
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1s2d3f4
      MYSQL_USER: project
      MYSQL_PASSWORD: a1s2d3f4
      MYSQL_DATABASE: sns
      TZ: Asia/Seoul
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exit | mysql -h localhost -P 3306 -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 2s
      retries: 10

  db.redis:
    container_name: db.redis
    image: redis:7.0.12-alpine
    restart: always
    volumes:
      - redis_db:/var/lib/redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5

  app:
    container_name: sns
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      db.mysql:
        condition: service_healthy
      db.redis:
        condition: service_healthy

volumes:
  mysql_db:
  redis_db:
