version: "3"
services:
  db.mysql:
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1s2d3f4
      MYSQL_USER : project
      MYSQL_PASSWORD: a1s2d3f4
      MYSQL_DATABASE: sns
      TZ: Asia/Seoul
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db.mysql

volumes:
  mysql_db: